name: Cancel
on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next
permissions:
  contents: read

jobs:
  cancel:
    permissions:
      actions: write # for styfle/cancel-workflow-action to cancel/stop running workflows
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: nodejs.yml
          access_token: ${{ github.token }}
